name: Windows
env:
  VK_VERSION: 1.3.224.1
on:
 workflow_dispatch:
 push:
   branches:
     - master

jobs:
  Windows:
    runs-on: windows-2022

    steps:
      - uses: microsoft/setup-msbuild@v1.1
      - uses: actions/checkout@v3

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.1.1
        with:
          version: $VK_VERSION
          cache: true
      - name: Build Rion Debug (x64)
        run: msbuild rion.sln /m /t:Rebuild /p:Configuration=Debug /p:Platform=x64
      - name: Upload Rion Debug (x64) artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Rion-Windows-debug-x64
          path: |
            Rion
            !Rion/**/*.obj
            !Rion/**/*.exp
            !Rion/**/*.ilk
            !Rion/**/*.lib
            !Rion/**/*.pdb
            !Rion/**/*.iobj
            !Rion/**/*.ipdb
      - name: Build Rion Release (x64)
        run: msbuild rion.sln /m /t:Rebuild /p:Configuration=Release /p:Platform=x64
      - name: Upload Rion Release (x64) artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Rion-Windows-release-x64
          path: |
            Rion
            !Rion/**/*.obj
            !Rion/**/*.exp
            !Rion/**/*.ilk
            !Rion/**/*.lib
            !Quake2/**/*.pdb
            !Quake2/**/*.iobj
            !Quake2/**/*.ipdb
